Bookstore: styling Branch
abenezer-addisu/React-Bookstore pull request #5
Opened 2023-06-23 18:14 UTC by abenezer-addisu

In this PR we:

- [ ] add fonts with font-awesome
- [ ] build book progress style
- [ ] refactor
- [ ] Added missing JSX elements
- [ ] Used to the Zeplin's design to do the styling

2023-06-23 18:31 UTC, levy002 requested changes
## Hello @abenezer-addisu   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 
- Good UI :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to adjust the background color on the category input in order to match the provided design.

  - ### YOUR DESIGN
  
   ![image](https://github.com/abenezer-addisu/React-Bookstore/assets/87197412/3a3e1c7e-d8db-468f-8135-1d9df31b56e3)

  - ### PROVIDED DESIGN
  
   ![image](https://github.com/abenezer-addisu/React-Bookstore/assets/87197412/b154d099-d10a-4a4b-bab1-584175213205)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 12:07 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @abenezer-addisu 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

### Highlights 🎯 
✔️ Descriptive PR
✔️ Applied styles according to Zeplin design 📌 
✔️ Linters are passing

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 12:07 UTC, codepantha commented on src/components/BookInput.js
> +          </select>
- [ ] Just like the previous reviewer suggested, please change the background color of the category select input to match the provided zeplin design as can be seen below 👇 
### Zeplin Design
![image](https://github.com/abenezer-addisu/React-Bookstore/assets/46839548/aa1d0cdf-035a-40c9-b15f-31a01c0e5394)

### Your Implementation
![image](https://github.com/abenezer-addisu/React-Bookstore/assets/46839548/07894573-39eb-4b97-a757-0177352e502b)

2023-06-24 19:47 UTC, Deepakdanger approved these changes
Hi @abenezer-addisu , 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 20:02 UTC, merged